# Generated by Django 5.2.3 on 2025-10-15 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("databaseHandler", "0002_batch"),
    ]

    operations = [
        migrations.CreateModel(
            name="foottraffic_batch_bridge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batchRef",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="databaseHandler.batch",
                    ),
                ),
                (
                    "dataRef",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="databaseHandler.foottraffic_fact",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="sched_batch_bridge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batchRef",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="databaseHandler.batch",
                    ),
                ),
                (
                    "dataRef",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="databaseHandler.schedule_dim",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ticket_batch_bridge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batchRef",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="databaseHandler.batch",
                    ),
                ),
                (
                    "dataRef",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="databaseHandler.ticket_dim",
                    ),
                ),
            ],
        ),
    ]
