# Generated by Django 5.2.3 on 2025-10-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("databaseHandler", "0005_deletioninfo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location_dim",
            name="location_name_abbreviated",
            field=models.TextField(max_length=255, unique=True),
        ),
    ]
