# Generated by Django 5.2.3 on 2025-10-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArimaInsights",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="ArimaPredictions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField()),
                ("location", models.TextField(max_length=20)),
                ("value", models.DecimalField(decimal_places=2, max_digits=255)),
                ("valueType", models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="PredictionPower",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.TextField(max_length=20)),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
