# Generated by Django 5.2.3 on 2025-10-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataAnalytics", "0003_ticketclustering"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketclustering",
            name="year",
            field=models.TextField(default=1900, max_length=5),
            preserve_default=False,
        ),
    ]
