# Generated by Django 5.2.7 on 2025-10-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataAnalytics', '0005_durationclustering'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusteringPower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.TextField(max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='GenderClustering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('female', models.DecimalField(decimal_places=2, max_digits=10)),
                ('male', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.TextField(max_length=20)),
                ('year', models.TextField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='OriginClustering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foreign', models.DecimalField(decimal_places=2, max_digits=10)),
                ('domestic', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.TextField(max_length=20)),
                ('year', models.TextField(max_length=5)),
            ],
        ),
    ]
