# Generated by Django 5.2.3 on 2025-10-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataAnalytics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="arimainsights",
            name="location",
            field=models.TextField(default="Unknown", max_length=20),
            preserve_default=False,
        ),
    ]
