# Generated by Django 5.2.3 on 2025-10-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataAnalytics", "0004_ticketclustering_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="DurationClustering",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("duration", models.DecimalField(decimal_places=2, max_digits=10)),
                ("value", models.IntegerField()),
                ("location", models.TextField(max_length=20)),
                ("year", models.TextField(max_length=5)),
            ],
        ),
    ]
