# Generated by Django 5.2.7 on 2025-10-25 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataAnalytics', '0006_clusteringpower_genderclustering_originclustering'),
    ]

    operations = [
        migrations.AddField(
            model_name='genderclustering',
            name='cluster',
            field=models.TextField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='originclustering',
            name='cluster',
            field=models.TextField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
