# Generated by Django 5.2.3 on 2025-10-02 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location_Dim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location_name_abbreviated", models.TextField(max_length=255)),
                (
                    "location_name_full",
                    models.TextField(blank=True, max_length=255, null=True),
                ),
                (
                    "location_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=255, null=True
                    ),
                ),
                (
                    "location_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=255, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Time_Dim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_year", models.TextField(max_length=5)),
                ("time_quarter", models.TextField(max_length=255)),
                ("time_month", models.TextField(max_length=255)),
                ("time_week", models.TextField(max_length=255)),
                ("time_day", models.DateField()),
                ("time_holiday", models.TextField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Ticket_Dim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticket_price_base",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "ticket_price_discounted",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "ticket_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="databaseHandler.location_dim",
                    ),
                ),
                (
                    "ticket_date",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="databaseHandler.time_dim",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Schedule_Dim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("schedule_openingtime", models.TimeField(null=True)),
                ("schedule_closingtime", models.TimeField(null=True)),
                (
                    "schedule_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="databaseHandler.location_dim",
                    ),
                ),
                (
                    "schedule_date",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="databaseHandler.time_dim",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Weather_Dim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weather_rainValue",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "weather_temperatureValue",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "weather_windValue",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "weather_time",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="databaseHandler.time_dim",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FootTraffic_Fact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fact_foreign", models.IntegerField()),
                ("fact_domestic", models.IntegerField()),
                ("fact_male", models.IntegerField()),
                ("fact_female", models.IntegerField()),
                ("fact_originUnknown", models.IntegerField()),
                ("fact_sexUnknown", models.IntegerField()),
                ("fact_uncategorized", models.IntegerField()),
                (
                    "fact_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="databaseHandler.location_dim",
                    ),
                ),
                (
                    "fact_time",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="databaseHandler.time_dim",
                    ),
                ),
                (
                    "fact_weather",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="databaseHandler.weather_dim",
                    ),
                ),
            ],
        ),
    ]
