# Generated by Django 5.2.3 on 2025-10-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "databaseHandler",
            "0003_foottraffic_batch_bridge_sched_batch_bridge_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="uploadtime",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
