# Generated by Django 5.2.3 on 2025-10-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("databaseHandler", "0006_alter_location_dim_location_name_abbreviated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location_dim",
            name="location_latitude",
            field=models.DecimalField(decimal_places=7, default=1, max_digits=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="location_dim",
            name="location_longitude",
            field=models.DecimalField(decimal_places=7, default=1, max_digits=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="location_dim",
            name="location_name_full",
            field=models.TextField(default="Narnia", max_length=255),
            preserve_default=False,
        ),
    ]
